// THIS FILE IS AUTOGENERATED BY axi_intercon_gen
// ANY MANUAL CHANGES WILL BE LOST
logic  [3:0] icache_awid;
logic [31:0] icache_awaddr;
logic  [7:0] icache_awlen;
logic  [2:0] icache_awsize;
logic  [1:0] icache_awburst;
logic        icache_awlock;
logic  [3:0] icache_awcache;
logic  [2:0] icache_awprot;
logic  [3:0] icache_awregion;
logic  [3:0] icache_awqos;
logic        icache_awvalid;
logic        icache_awready;
logic  [3:0] icache_arid;
logic [31:0] icache_araddr;
logic  [7:0] icache_arlen;
logic  [2:0] icache_arsize;
logic  [1:0] icache_arburst;
logic        icache_arlock;
logic  [3:0] icache_arcache;
logic  [2:0] icache_arprot;
logic  [3:0] icache_arregion;
logic  [3:0] icache_arqos;
logic        icache_arvalid;
logic        icache_arready;
logic [31:0] icache_wdata;
logic  [3:0] icache_wstrb;
logic        icache_wlast;
logic        icache_wvalid;
logic        icache_wready;
logic  [3:0] icache_bid;
logic  [1:0] icache_bresp;
logic        icache_bvalid;
logic        icache_bready;
logic  [3:0] icache_rid;
logic [31:0] icache_rdata;
logic  [1:0] icache_rresp;
logic        icache_rlast;
logic        icache_rvalid;
logic        icache_rready;
logic  [3:0] dcache_awid;
logic [31:0] dcache_awaddr;
logic  [7:0] dcache_awlen;
logic  [2:0] dcache_awsize;
logic  [1:0] dcache_awburst;
logic        dcache_awlock;
logic  [3:0] dcache_awcache;
logic  [2:0] dcache_awprot;
logic  [3:0] dcache_awregion;
logic  [3:0] dcache_awqos;
logic        dcache_awvalid;
logic        dcache_awready;
logic  [3:0] dcache_arid;
logic [31:0] dcache_araddr;
logic  [7:0] dcache_arlen;
logic  [2:0] dcache_arsize;
logic  [1:0] dcache_arburst;
logic        dcache_arlock;
logic  [3:0] dcache_arcache;
logic  [2:0] dcache_arprot;
logic  [3:0] dcache_arregion;
logic  [3:0] dcache_arqos;
logic        dcache_arvalid;
logic        dcache_arready;
logic [31:0] dcache_wdata;
logic  [3:0] dcache_wstrb;
logic        dcache_wlast;
logic        dcache_wvalid;
logic        dcache_wready;
logic  [3:0] dcache_bid;
logic  [1:0] dcache_bresp;
logic        dcache_bvalid;
logic        dcache_bready;
logic  [3:0] dcache_rid;
logic [31:0] dcache_rdata;
logic  [1:0] dcache_rresp;
logic        dcache_rlast;
logic        dcache_rvalid;
logic        dcache_rready;
logic  [4:0] mem_one_awid;
logic [31:0] mem_one_awaddr;
logic  [7:0] mem_one_awlen;
logic  [2:0] mem_one_awsize;
logic  [1:0] mem_one_awburst;
logic        mem_one_awlock;
logic  [3:0] mem_one_awcache;
logic  [2:0] mem_one_awprot;
logic  [3:0] mem_one_awregion;
logic  [3:0] mem_one_awqos;
logic        mem_one_awvalid;
logic        mem_one_awready;
logic  [4:0] mem_one_arid;
logic [31:0] mem_one_araddr;
logic  [7:0] mem_one_arlen;
logic  [2:0] mem_one_arsize;
logic  [1:0] mem_one_arburst;
logic        mem_one_arlock;
logic  [3:0] mem_one_arcache;
logic  [2:0] mem_one_arprot;
logic  [3:0] mem_one_arregion;
logic  [3:0] mem_one_arqos;
logic        mem_one_arvalid;
logic        mem_one_arready;
logic [31:0] mem_one_wdata;
logic  [3:0] mem_one_wstrb;
logic        mem_one_wlast;
logic        mem_one_wvalid;
logic        mem_one_wready;
logic  [4:0] mem_one_bid;
logic  [1:0] mem_one_bresp;
logic        mem_one_bvalid;
logic        mem_one_bready;
logic  [4:0] mem_one_rid;
logic [31:0] mem_one_rdata;
logic  [1:0] mem_one_rresp;
logic        mem_one_rlast;
logic        mem_one_rvalid;
logic        mem_one_rready;

axi_intercon axi_intercon
   (.clk_i              (clk),
    .rst_ni             (rst_n),
    .i_icache_awid      (icache_awid),
    .i_icache_awaddr    (icache_awaddr),
    .i_icache_awlen     (icache_awlen),
    .i_icache_awsize    (icache_awsize),
    .i_icache_awburst   (icache_awburst),
    .i_icache_awlock    (icache_awlock),
    .i_icache_awcache   (icache_awcache),
    .i_icache_awprot    (icache_awprot),
    .i_icache_awregion  (icache_awregion),
    .i_icache_awqos     (icache_awqos),
    .i_icache_awvalid   (icache_awvalid),
    .o_icache_awready   (icache_awready),
    .i_icache_arid      (icache_arid),
    .i_icache_araddr    (icache_araddr),
    .i_icache_arlen     (icache_arlen),
    .i_icache_arsize    (icache_arsize),
    .i_icache_arburst   (icache_arburst),
    .i_icache_arlock    (icache_arlock),
    .i_icache_arcache   (icache_arcache),
    .i_icache_arprot    (icache_arprot),
    .i_icache_arregion  (icache_arregion),
    .i_icache_arqos     (icache_arqos),
    .i_icache_arvalid   (icache_arvalid),
    .o_icache_arready   (icache_arready),
    .i_icache_wdata     (icache_wdata),
    .i_icache_wstrb     (icache_wstrb),
    .i_icache_wlast     (icache_wlast),
    .i_icache_wvalid    (icache_wvalid),
    .o_icache_wready    (icache_wready),
    .o_icache_bid       (icache_bid),
    .o_icache_bresp     (icache_bresp),
    .o_icache_bvalid    (icache_bvalid),
    .i_icache_bready    (icache_bready),
    .o_icache_rid       (icache_rid),
    .o_icache_rdata     (icache_rdata),
    .o_icache_rresp     (icache_rresp),
    .o_icache_rlast     (icache_rlast),
    .o_icache_rvalid    (icache_rvalid),
    .i_icache_rready    (icache_rready),
    .i_dcache_awid      (dcache_awid),
    .i_dcache_awaddr    (dcache_awaddr),
    .i_dcache_awlen     (dcache_awlen),
    .i_dcache_awsize    (dcache_awsize),
    .i_dcache_awburst   (dcache_awburst),
    .i_dcache_awlock    (dcache_awlock),
    .i_dcache_awcache   (dcache_awcache),
    .i_dcache_awprot    (dcache_awprot),
    .i_dcache_awregion  (dcache_awregion),
    .i_dcache_awqos     (dcache_awqos),
    .i_dcache_awvalid   (dcache_awvalid),
    .o_dcache_awready   (dcache_awready),
    .i_dcache_arid      (dcache_arid),
    .i_dcache_araddr    (dcache_araddr),
    .i_dcache_arlen     (dcache_arlen),
    .i_dcache_arsize    (dcache_arsize),
    .i_dcache_arburst   (dcache_arburst),
    .i_dcache_arlock    (dcache_arlock),
    .i_dcache_arcache   (dcache_arcache),
    .i_dcache_arprot    (dcache_arprot),
    .i_dcache_arregion  (dcache_arregion),
    .i_dcache_arqos     (dcache_arqos),
    .i_dcache_arvalid   (dcache_arvalid),
    .o_dcache_arready   (dcache_arready),
    .i_dcache_wdata     (dcache_wdata),
    .i_dcache_wstrb     (dcache_wstrb),
    .i_dcache_wlast     (dcache_wlast),
    .i_dcache_wvalid    (dcache_wvalid),
    .o_dcache_wready    (dcache_wready),
    .o_dcache_bid       (dcache_bid),
    .o_dcache_bresp     (dcache_bresp),
    .o_dcache_bvalid    (dcache_bvalid),
    .i_dcache_bready    (dcache_bready),
    .o_dcache_rid       (dcache_rid),
    .o_dcache_rdata     (dcache_rdata),
    .o_dcache_rresp     (dcache_rresp),
    .o_dcache_rlast     (dcache_rlast),
    .o_dcache_rvalid    (dcache_rvalid),
    .i_dcache_rready    (dcache_rready),
    .o_mem_one_awid     (mem_one_awid),
    .o_mem_one_awaddr   (mem_one_awaddr),
    .o_mem_one_awlen    (mem_one_awlen),
    .o_mem_one_awsize   (mem_one_awsize),
    .o_mem_one_awburst  (mem_one_awburst),
    .o_mem_one_awlock   (mem_one_awlock),
    .o_mem_one_awcache  (mem_one_awcache),
    .o_mem_one_awprot   (mem_one_awprot),
    .o_mem_one_awregion (mem_one_awregion),
    .o_mem_one_awqos    (mem_one_awqos),
    .o_mem_one_awvalid  (mem_one_awvalid),
    .i_mem_one_awready  (mem_one_awready),
    .o_mem_one_arid     (mem_one_arid),
    .o_mem_one_araddr   (mem_one_araddr),
    .o_mem_one_arlen    (mem_one_arlen),
    .o_mem_one_arsize   (mem_one_arsize),
    .o_mem_one_arburst  (mem_one_arburst),
    .o_mem_one_arlock   (mem_one_arlock),
    .o_mem_one_arcache  (mem_one_arcache),
    .o_mem_one_arprot   (mem_one_arprot),
    .o_mem_one_arregion (mem_one_arregion),
    .o_mem_one_arqos    (mem_one_arqos),
    .o_mem_one_arvalid  (mem_one_arvalid),
    .i_mem_one_arready  (mem_one_arready),
    .o_mem_one_wdata    (mem_one_wdata),
    .o_mem_one_wstrb    (mem_one_wstrb),
    .o_mem_one_wlast    (mem_one_wlast),
    .o_mem_one_wvalid   (mem_one_wvalid),
    .i_mem_one_wready   (mem_one_wready),
    .i_mem_one_bid      (mem_one_bid),
    .i_mem_one_bresp    (mem_one_bresp),
    .i_mem_one_bvalid   (mem_one_bvalid),
    .o_mem_one_bready   (mem_one_bready),
    .i_mem_one_rid      (mem_one_rid),
    .i_mem_one_rdata    (mem_one_rdata),
    .i_mem_one_rresp    (mem_one_rresp),
    .i_mem_one_rlast    (mem_one_rlast),
    .i_mem_one_rvalid   (mem_one_rvalid),
    .o_mem_one_rready   (mem_one_rready));

